### ISSUE TITLE
which plugin do you use in this gif

### ISSUE THREAD

**Issue by glepnir** [t9md/vim-transform#2]
it  looks like AndrewRadev/splitjoin.vim,but more useful.
![transform](https://user-images.githubusercontent.com/41671631/55528825-dba94280-56d0-11e9-89b1-35fcd5e20324.gif)

**Comment by t9md** [comment]
Can not remember! Maybe I think it was https://www.cockos.com/licecap/.
I always use LiceCap for Mac, but this GIF is too old.

**Comment by t9md** [comment]
Oh,,, you are asking plugin for text-manipulation?
That is this plugin `vim-transform` with some extra configuration.
Check example or documentation in this plugin.

**Comment by glepnir** [comment]
> Oh,,, you are asking plugin for text-manipulation?
> That is this plugin `vim-transform` with some extra configuration.
> Check example or documentation in this plugin.

in gif  you do this` fmt net/http os etc` then it becomes 
```
"fmt"
"net/http"
etc
```
this option look like the plugin that `AndrewRadev/splitjoin.vim` ,but i almost use it. i cant do this.

**Comment by t9md** [comment]
`AndrewRadev/splitjoin.vim` is not related.
This project page is `vim-transform` plugin page, so I'm demonstrating `vim-transform` feature.
Read and experiment with `vim-transform` package, you should be able to do the same operation in GIF.

**Comment by glepnir** [comment]
@t9md  thanks for your reply, i read the plugins. It's amazing. I thought it could only be translated. 
Can it do this splitting and splitjoin？ i will  try it。
