### ISSUE TITLE
:Tranform works, but mapping to <Plug>(transform) doesn't

### ISSUE THREAD

**Issue by rrichardson** [t9md/vim-transform#3]
Thanks for making such a great plugin.  This is just what I needed to speed up authoring OpenAPI specs. 

I have followed your instructions for the custom handler, https://github.com/t9md/vim-transform/tree/master/misc/ruby_handler . 

I changed out the ruby code for nodejs.  The transformer I built works, however, it only works when I do a visual select and run :Transform.  If I tap  alt+t as per the mapping,  nothing happens. 

I am a newbie to vim script and am not sure what I'm missing in order to make the mappings work: 
Here's the relevant part of my vimrc : 

```
let g:transform = {}
let g:transform.options = {}
let g:transform.options.enable_default_config = 0
let g:transform.options.path = "$HOME/.vim-transform"

function! g:transform._(e)
  " To avoid mess in passing `env` as argment.
  " We serialize env to JSON and pass as first line of STDIN.
  " handler.rb should pop first line of STDIN and decode as JSON.
  " rest of STDIN is original STDIN in handler.rb
  let STDIN = [a:e.toJSON()] + a:e.content.all
  call a:e.content.update(STDIN)
  echom "calling bin/index.js"
  call a:e.run('bin/index.js')
endfunction

nmap <M-t> <Plug>(g:transform)
xmap <M-t> <Plug>(g:transform)
imap <M-t> <Plug>(g:transform)
```

**Comment by t9md** [comment]
Maybe `alt` is a kind of a tricky key in the terminal.  How about changing your key like `xmap tt <Plug>(g:transform)`?

**Comment by rrichardson** [comment]
`xmap tt <Plug>(transform)`  worked (I think I added the g:transform at some point when trying to figure out the problem) 

I think I like tt better than alt-t anyways.  Thanks!

**Comment by t9md** [comment]
Great!
